college:
   univ: local
   
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
           
---
spring:
  profiles: dev
  
college:
   univ: local_dev

---   
spring:
  profiles: test
  
college:
   univ: local_test

---
spring:
  profiles: preprod
  
college:
   univ: local_preprod
---   
spring:
  profiles: prod
  
college:
   univ: local_prod

           
     